version: '3.7'

services:
  mysql:
    build: ./mysql/
    cap_add:
      - SYS_NICE
    command: --authentication_policy=mysql_native_password
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      typescript-magazine:
        ipv4_address: 172.22.0.3

  server:
    depends_on:
      - mysql
    build: ./app/
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=172.22.0.3
    volumes:
      - ./app/upload:/app/upload
    ports:
      - 80:5000
    networks:
      typescript-magazine:
        ipv4_address: 172.22.0.4

# TODO : sudo docker network create --gateway 172.22.0.1 --subnet 172.22.0.0/16 --driver=bridge typescript-magazine
networks:
  typescript-magazine:
    internal: true
    external: true
