openapi: '3.0.0'
info:
  version: '1.0.0'
  description: '항헤99 주특기 심화 - Magazine API'
  title: 'Swagger Magazine'

servers:
  - description: '로컬 서버'
    url: 'http://localhost:5000/api'
  - description: '클라우드 서버'
    url: 'http://146.56.187.171/api'

tags:
  - name: 'users'
    description: '사용자 API { 회원가입 / 로그인 / 인증 확인 }'
  - name: 'posts'
    description: '게시물 API { 조회 / 생성 / 수정 / 삭제 }'
  - name: 'like'
    description: '게시물 좋아요 상태'
  - name: 'comment'
    description: '댓글 조회 / 생성 / 수정 / 삭제'

schemes:
  - 'http'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /users/signup:
    post:
      tags:
        - users
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                nickname:
                  type: string
                password:
                  type: string
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                nickname:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '400':
          description: Bad Requset
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '409':
          description: Comflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
  /users/signin:
    post:
      tags:
        - users
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Ok
          headers:
            Set-Cookie:
              token:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
  /users/auth:
    get:
      tags:
        - users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  user:
                    type: object
                    properties:
                      user_id:
                        type: integer
                      email:
                        type: string
                      nickname:
                        type: string
                      role:
                        type: integer
        '402':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
  /posts:
    get:
      tags:
        - posts
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  rows:
                    type: array
                    items:
                      type: object
                      properties:
                        post_id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                        image_url:
                          type: string
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
                        user:
                          type: object
                          properties:
                            user_id:
                              type: integer
                            email:
                              type: string
                            nickname:
                              type: string
                        likes:
                          type: array
                          items:
                            type: object
                            properties:
                              user_id:
                                type: integer
    post:
      tags:
        - posts
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                content:
                  type: string
                image:
                  type: string
                  format: binary
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '400':
          description: Bad Requset
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
  /posts/{post_id}:
    get:
      tags:
        - posts
      parameters:
        - in: path
          name: post_id
          schema:
            type: integer
            minimum: 1
          required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  row:
                    type: object
                    properties:
                      post_id:
                        type: integer
                      title:
                        type: string
                      content:
                        type: string
                      image_url:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      user:
                        type: object
                        properties:
                          user_id:
                            type: integer
                          email:
                            type: string
                          nickname:
                            type: string
                      likes:
                        type: array
                        items:
                          type: object
                          properties:
                            user_id:
                              type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
    patch:
      tags:
        - posts
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: post_id
          schema:
            type: integer
            minimum: 1
          required: true
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                content:
                  type: string
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '400':
          description: Bad Requset
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
    delete:
      tags:
        - posts
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: post_id
          schema:
            type: integer
            minimum: 1
          required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
